export const MOCK_CLIENTS = [
  {
    id: "c1",
    name: "Anand Kumar",
    company: "FinTech Solutions Pvt Ltd",
    email: "anand.kumar@fintech.in",
    phone: "+91 98765 43210",
    status: "Lead",
    leadType: "Hot",
    avatar: "Anand.png",
    joinedDate: "2023-11-15",
    lastContact: "2023-11-20",
    industry: "Financial Services",
    notes:
      "Very interested in our API integration. Needs a demo by next Tuesday. Decision maker.",
  },
  {
    id: "c2",
    name: "Vikram Malhotra",
    company: "Malhotra Logistics",
    email: "vikram@malhotra.com",
    phone: "+91 98123 45678",
    status: "Lead",
    leadType: "Warm",
    avatar: "https://picsum.photos/100/100?random=12",
    joinedDate: "2023-11-10",
    lastContact: "2023-11-18",
    industry: "Logistics",
    notes:
      "Checking budget for the next quarter. Currently using a manual system. Open to a pilot program.",
  },
  {
    id: "c3",
    name: "Kavita Rao",
    company: "Urban Health Care",
    email: "kavita.rao@urbanhealth.org",
    phone: "+91 99887 76655",
    status: "Lead",
    leadType: "Cold",
    avatar: "https://picsum.photos/100/100?random=13",
    joinedDate: "2023-10-05",
    lastContact: "2023-11-10",
    industry: "Healthcare",
    notes:
      "Early stage discussion. Need to follow up in 3 months once their new facility is ready.",
  },
  {
    id: "c4",
    name: "Suresh Raina",
    company: "Nexus Real Estate",
    email: "suresh@nexus.co.in",
    phone: "+91 97654 32109",
    status: "Active",
    avatar: "https://picsum.photos/100/100?random=14",
    joinedDate: "2023-01-10",
    lastContact: "2023-11-15",
    industry: "Real Estate",
    notes:
      "Long-term client. Satisfied with the current CRM flow. Looking to upgrade to the enterprise plan.",
  },
  {
    id: "c5",
    name: "Priya Sharma",
    company: "TechVision Inc",
    email: "priya.sharma@techvision.com",
    phone: "+91 98765 12345",
    status: "Active",
    leadType: "Hot",
    avatar: "https://picsum.photos/100/100?random=15",
    joinedDate: "2023-08-20",
    lastContact: "2023-11-22",
    industry: "Technology",
    notes:
      "Excellent growth trajectory. Very responsive to new features. Expanding team.",
  },
  {
    id: "c6",
    name: "Rajesh Patel",
    company: "Global Trading Solutions",
    email: "rajesh@globaltrading.com",
    phone: "+91 99876 54321",
    status: "Active",
    avatar: "https://picsum.photos/100/100?random=16",
    joinedDate: "2023-07-15",
    lastContact: "2023-11-21",
    industry: "Trading",
    notes:
      "Strategic partner. Regular quarterly reviews. High revenue account.",
  },
  {
    id: "c7",
    name: "Neha Gupta",
    company: "EduTech Academy",
    email: "neha@educator.in",
    phone: "+91 97654 32109",
    status: "Lead",
    leadType: "Warm",
    avatar: "https://picsum.photos/100/100?random=17",
    joinedDate: "2023-10-25",
    lastContact: "2023-11-19",
    industry: "Education",
    notes: "Interest in student management features. Budget approval pending.",
  },
  {
    id: "c8",
    name: "Arun Verma",
    company: "BuildRight Construction",
    email: "arun@buildright.co.in",
    phone: "+91 98765 11223",
    status: "Active",
    avatar: "https://picsum.photos/100/100?random=18",
    joinedDate: "2023-06-10",
    lastContact: "2023-11-20",
    industry: "Construction",
    notes: "Long-standing partner. Multiple project tracking. Very satisfied.",
  },
  {
    id: "c9",
    name: "Deepak Singh",
    company: "RetailMax Networks",
    email: "deepak@retailmax.com",
    phone: "+91 99998 88777",
    status: "Lead",
    leadType: "Cold",
    avatar: "https://picsum.photos/100/100?random=19",
    joinedDate: "2023-11-01",
    lastContact: "2023-11-15",
    industry: "Retail",
    notes:
      "Inbound inquiry. Evaluating multiple solutions. Demo scheduled for next month.",
  },
  {
    id: "c10",
    name: "Sakshi Mehta",
    company: "HealthCare Plus Hospitals",
    email: "sakshi@healthcareplus.org",
    phone: "+91 98765 00111",
    status: "Active",
    avatar: "https://picsum.photos/100/100?random=20",
    joinedDate: "2023-05-12",
    lastContact: "2023-11-22",
    industry: "Healthcare",
    notes: "Key account. 3 departments using system. Wants advanced analytics.",
  },
  {
    id: "c11",
    name: "Vikram Singh",
    company: "AutoParts Hub",
    email: "vikram.singh@autoparts.in",
    phone: "+91 97777 66655",
    status: "Lead",
    leadType: "Warm",
    avatar: "https://picsum.photos/100/100?random=21",
    joinedDate: "2023-10-30",
    lastContact: "2023-11-18",
    industry: "Automotive",
    notes:
      "Good fit for our platform. Needs custom integration with ERP system.",
  },
  {
    id: "c12",
    name: "Pooja Desai",
    company: "CloudSync Technologies",
    email: "pooja.d@cloudsync.tech",
    phone: "+91 99999 11223",
    status: "Active",
    avatar: "https://picsum.photos/100/100?random=22",
    joinedDate: "2023-04-08",
    lastContact: "2023-11-21",
    industry: "Cloud Services",
    notes:
      "Technical integration partner. API excellence. Growing partnership.",
  },
  {
    id: "c13",
    name: "Manish Kumar",
    company: "Premium Hotels Group",
    email: "manish.k@premiumhotels.com",
    phone: "+91 98765 55678",
    status: "Active",
    avatar: "https://picsum.photos/100/100?random=23",
    joinedDate: "2023-09-14",
    lastContact: "2023-11-20",
    industry: "Hospitality",
    notes:
      "Multi-property rollout. Satisfied with customization. Referral source.",
  },
];

export const MOCK_FOLLOW_UPS = [
  // TODAY - Overdue/Due Today (10)
  {
    id: "f1",
    clientId: "c2",
    title: "Call James regarding logistics MVP",
    description: "Discuss the MVP scope and timeline",
    dueDate: new Date().toISOString(),
    followup_date: new Date().toISOString().split("T")[0],
    status: "pending",
    followup_status: "pending",
    priority: "High",
    followup_mode: "call",
    follow_brief: "Need to confirm budget and timeline",
  },
  {
    id: "f2",
    clientId: "c1",
    title: "Send security audit report",
    description: "Complete security audit documentation",
    dueDate: new Date(Date.now() - 86400000).toISOString(),
    followup_date: new Date(Date.now() - 86400000).toISOString().split("T")[0],
    status: "pending",
    followup_status: "pending",
    priority: "Medium",
    followup_mode: "email",
    follow_brief: "Security audit findings and recommendations",
  },
  {
    id: "f3",
    clientId: "c3",
    title: "Follow up on dashboard latency ticket",
    description: "Check on performance improvement status",
    dueDate: new Date(Date.now() - 172800000).toISOString(),
    followup_date: new Date(Date.now() - 172800000).toISOString().split("T")[0],
    status: "pending",
    followup_status: "pending",
    priority: "Low",
    followup_mode: "call",
    follow_brief: "Dashboard optimization progress",
  },
  {
    id: "f4",
    clientId: "c1",
    title: "API integration demo session",
    description: "Conduct detailed API integration walkthrough",
    dueDate: new Date(Date.now()).toISOString(),
    followup_date: new Date(Date.now()).toISOString().split("T")[0],
    status: "pending",
    followup_status: "pending",
    priority: "High",
    followup_mode: "meeting",
    follow_brief: "Demo API endpoints and sandbox environment",
  },
  {
    id: "f5",
    clientId: "c2",
    title: "Send pricing proposal to Vikram",
    description: "Customized pricing proposal for logistics platform",
    dueDate: new Date(Date.now() - 259200000).toISOString(),
    followup_date: new Date(Date.now() - 259200000).toISOString().split("T")[0],
    status: "pending",
    followup_status: "pending",
    priority: "High",
    followup_mode: "email",
    follow_brief: "Enterprise tier pricing with volume discounts",
  },
  {
    id: "f6",
    clientId: "c4",
    title: "Upgrade planning session",
    description: "Discuss enterprise plan migration",
    dueDate: new Date(Date.now() - 86400000).toISOString(),
    followup_date: new Date(Date.now() - 86400000).toISOString().split("T")[0],
    status: "pending",
    followup_status: "pending",
    priority: "Medium",
    followup_mode: "meeting",
    follow_brief: "Enterprise features and implementation timeline",
  },
  {
    id: "f7",
    clientId: "c3",
    title: "Check facility readiness",
    description: "Verify new facility is ready for system deployment",
    dueDate: new Date(Date.now()).toISOString(),
    followup_date: new Date(Date.now()).toISOString().split("T")[0],
    status: "pending",
    followup_status: "pending",
    priority: "Low",
    followup_mode: "call",
    follow_brief: "Infrastructure readiness assessment",
  },
  {
    id: "f8",
    clientId: "c1",
    title: "Compliance documentation review",
    description: "Review compliance requirements and standards",
    dueDate: new Date(Date.now() - 172800000).toISOString(),
    followup_date: new Date(Date.now() - 172800000).toISOString().split("T")[0],
    status: "pending",
    followup_status: "pending",
    priority: "High",
    followup_mode: "email",
    follow_brief: "ISO 27001 and GDPR compliance checklist",
  },
  {
    id: "f16",
    clientId: "c5",
    title: "Quarterly performance review call",
    description: "Review KPIs and discuss growth strategies",
    dueDate: new Date(Date.now()).toISOString(),
    followup_date: new Date(Date.now()).toISOString().split("T")[0],
    status: "pending",
    followup_status: "pending",
    priority: "High",
    followup_mode: "meeting",
    follow_brief: "Q4 performance analysis",
  },
  {
    id: "f17",
    clientId: "c8",
    title: "Check project milestone status",
    description: "Verify all construction phase milestones achieved",
    dueDate: new Date(Date.now() - 345600000).toISOString(),
    followup_date: new Date(Date.now() - 345600000).toISOString().split("T")[0],
    status: "pending",
    followup_status: "pending",
    priority: "Medium",
    followup_mode: "call",
    follow_brief: "Current project status update",
  },

  // UPCOMING - Future dates (10+)
  {
    id: "f9",
    clientId: "c2",
    title: "Integration testing kickoff",
    description: "Start integration testing phase",
    dueDate: new Date(Date.now() + 345600000).toISOString(),
    followup_date: new Date(Date.now() + 345600000).toISOString().split("T")[0],
    status: "pending",
    followup_status: "pending",
    priority: "High",
    followup_mode: "meeting",
    follow_brief: "QA plan and testing schedule",
  },
  {
    id: "f10",
    clientId: "c4",
    title: "Quarterly business review",
    description: "Review performance metrics and next quarter goals",
    dueDate: new Date(Date.now() + 604800000).toISOString(),
    followup_date: new Date(Date.now() + 604800000).toISOString().split("T")[0],
    status: "pending",
    followup_status: "pending",
    priority: "Medium",
    followup_mode: "meeting",
    follow_brief: "Performance analysis and strategic planning",
  },
  {
    id: "f11",
    clientId: "c3",
    title: "Budget approval follow-up",
    description: "Check on budget allocation status",
    dueDate: new Date(Date.now() + 86400000).toISOString(),
    followup_date: new Date(Date.now() + 86400000).toISOString().split("T")[0],
    status: "pending",
    followup_status: "pending",
    priority: "Medium",
    followup_mode: "call",
    follow_brief: "FY budget commitment confirmation",
  },
  {
    id: "f12",
    clientId: "c1",
    title: "User training session scheduling",
    description: "Schedule training for end users",
    dueDate: new Date(Date.now() + 432000000).toISOString(),
    followup_date: new Date(Date.now() + 432000000).toISOString().split("T")[0],
    status: "pending",
    followup_status: "pending",
    priority: "Medium",
    followup_mode: "email",
    follow_brief: "Training calendar and materials preparation",
  },
  {
    id: "f13",
    clientId: "c2",
    title: "Contract finalization call",
    description: "Final contract review and signature",
    dueDate: new Date(Date.now() + 259200000).toISOString(),
    followup_date: new Date(Date.now() + 259200000).toISOString().split("T")[0],
    status: "pending",
    followup_status: "pending",
    priority: "High",
    followup_mode: "call",
    follow_brief: "Contract amendment discussion and closure",
  },
  {
    id: "f14",
    clientId: "c4",
    title: "Support team handover",
    description: "Transfer account to dedicated support team",
    dueDate: new Date(Date.now() + 172800000).toISOString(),
    followup_date: new Date(Date.now() + 172800000).toISOString().split("T")[0],
    status: "pending",
    followup_status: "pending",
    priority: "Low",
    followup_mode: "email",
    follow_brief: "Introduce support team and escalation process",
  },
  {
    id: "f15",
    clientId: "c3",
    title: "Demo with stakeholders",
    description: "Present solution to hospital stakeholders",
    dueDate: new Date(Date.now() + 518400000).toISOString(),
    followup_date: new Date(Date.now() + 518400000).toISOString().split("T")[0],
    status: "pending",
    followup_status: "pending",
    priority: "High",
    followup_mode: "meeting",
    follow_brief: "Live platform demo and Q&A session",
  },
  {
    id: "f18",
    clientId: "c6",
    title: "Executive steering committee meeting",
    description: "Present platform ROI metrics and future roadmap",
    dueDate: new Date(Date.now() + 777600000).toISOString(),
    followup_date: new Date(Date.now() + 777600000).toISOString().split("T")[0],
    status: "pending",
    followup_status: "pending",
    priority: "High",
    followup_mode: "meeting",
    follow_brief: "Executive level discussion on strategic initiatives",
  },
  {
    id: "f19",
    clientId: "c7",
    title: "Student management feature walkthrough",
    description:
      "Show EduTech team comprehensive student tracking capabilities",
    dueDate: new Date(Date.now() + 172800000).toISOString(),
    followup_date: new Date(Date.now() + 172800000).toISOString().split("T")[0],
    status: "pending",
    followup_status: "pending",
    priority: "Medium",
    followup_mode: "meeting",
    follow_brief: "Education-specific features demo",
  },
  {
    id: "f20",
    clientId: "c9",
    title: "RetailMax store manager training",
    description: "Train on-site team on system functionalities",
    dueDate: new Date(Date.now() + 864000000).toISOString(),
    followup_date: new Date(Date.now() + 864000000).toISOString().split("T")[0],
    status: "pending",
    followup_status: "pending",
    priority: "Medium",
    followup_mode: "meeting",
    follow_brief: "Multi-store training program",
  },
  {
    id: "f21",
    clientId: "c10",
    title: "Healthcare compliance audit",
    description: "Verify system meets HIPAA requirements",
    dueDate: new Date(Date.now() + 432000000).toISOString(),
    followup_date: new Date(Date.now() + 432000000).toISOString().split("T")[0],
    status: "pending",
    followup_status: "pending",
    priority: "High",
    followup_mode: "meeting",
    follow_brief: "Compliance verification and certification",
  },
  {
    id: "f22",
    clientId: "c11",
    title: "ERP integration planning",
    description: "Discuss technical architecture and data mapping",
    dueDate: new Date(Date.now() + 604800000).toISOString(),
    followup_date: new Date(Date.now() + 604800000).toISOString().split("T")[0],
    status: "pending",
    followup_status: "pending",
    priority: "High",
    followup_mode: "meeting",
    follow_brief: "ERP system integration specifications",
  },
  {
    id: "f23",
    clientId: "c12",
    title: "API partner integration review",
    description: "Technical review of API integration capabilities",
    dueDate: new Date(Date.now() + 345600000).toISOString(),
    followup_date: new Date(Date.now() + 345600000).toISOString().split("T")[0],
    status: "pending",
    followup_status: "pending",
    priority: "Medium",
    followup_mode: "meeting",
    follow_brief: "API documentation and sandbox access",
  },
];

export const MOCK_PROJECTS = [
  // PENDING - Status: Pending (10)
  {
    id: "p1",
    clientId: "c1",
    name: "Security Infrastructure Audit",
    status: "Pending",
    budget: 45000,
    deadline: "2026-03-15",
    progress: 15,
    priority: "High",
    category: "Tech",
  },
  {
    id: "p2",
    clientId: "c3",
    name: "Healthcare Portal Development",
    status: "Pending",
    budget: 85000,
    deadline: "2026-04-20",
    progress: 5,
    priority: "Critical",
    category: "Tech",
  },
  {
    id: "p3",
    clientId: "c7",
    name: "EduTech Platform Integration",
    status: "Pending",
    budget: 35000,
    deadline: "2026-03-30",
    progress: 0,
    priority: "High",
    category: "Tech",
  },
  {
    id: "p15",
    clientId: "c9",
    name: "Retail CRM Setup",
    status: "Pending",
    budget: 50000,
    deadline: "2026-05-01",
    progress: 10,
    priority: "Medium",
    category: "Tech",
  },
  {
    id: "p16",
    clientId: "c10",
    name: "Healthcare Analytics Module",
    status: "Pending",
    budget: 90000,
    deadline: "2026-06-10",
    progress: 2,
    priority: "High",
    category: "Tech",
  },
  {
    id: "p17",
    clientId: "c11",
    name: "Auto Parts Inventory Sync",
    status: "Pending",
    budget: 30000,
    deadline: "2026-04-25",
    progress: 0,
    priority: "Medium",
    category: "Tech",
  },
  {
    id: "p18",
    clientId: "c12",
    name: "Cloud Backup Implementation",
    status: "Pending",
    budget: 40000,
    deadline: "2026-05-15",
    progress: 5,
    priority: "Medium",
    category: "Tech",
  },
  {
    id: "p19",
    clientId: "c13",
    name: "Hotel Loyalty Program Integration",
    status: "Pending",
    budget: 55000,
    deadline: "2026-06-30",
    progress: 0,
    priority: "High",
    category: "Tech",
  },
  {
    id: "p20",
    clientId: "c5",
    name: "Analytics AI Module",
    status: "Pending",
    budget: 65000,
    deadline: "2026-05-20",
    progress: 8,
    priority: "Critical",
    category: "Tech",
  },
  {
    id: "p21",
    clientId: "c6",
    name: "Trading Data Pipeline",
    status: "Pending",
    budget: 72000,
    deadline: "2026-06-05",
    progress: 12,
    priority: "High",
    category: "Tech",
  },
  {
    id: "p41",
    clientId: "c8",
    name: "Media Asset Library Setup",
    status: "Pending",
    budget: 30000,
    deadline: "2026-05-12",
    progress: 5,
    priority: "Medium",
    category: "Media",
  },
  {
    id: "p42",
    clientId: "c9",
    name: "Social Campaign Planning",
    status: "Pending",
    budget: 45000,
    deadline: "2026-05-25",
    progress: 8,
    priority: "High",
    category: "Media",
  },
  {
    id: "p43",
    clientId: "c10",
    name: "Video Production Coordination",
    status: "Pending",
    budget: 60000,
    deadline: "2026-06-10",
    progress: 2,
    priority: "High",
    category: "Media",
  },

  // IN PROGRESS - Status: In Progress (10)
  {
    id: "p4",
    clientId: "c1",
    name: "API Integration Phase 2",
    status: "In Progress",
    budget: 55000,
    deadline: "2026-02-28",
    progress: 65,
    priority: "High",
    category: "Tech",
  },
  {
    id: "p5",
    clientId: "c2",
    name: "Logistics MVP Development",
    status: "In Progress",
    budget: 120000,
    deadline: "2026-03-15",
    progress: 58,
    priority: "Critical",
    category: "Tech",
  },
  {
    id: "p6",
    clientId: "c5",
    name: "Analytics Dashboard Enhancement",
    status: "In Progress",
    budget: 28000,
    deadline: "2026-02-15",
    progress: 72,
    priority: "Medium",
    category: "Tech",
  },
  {
    id: "p7",
    clientId: "c8",
    name: "Project Management Module",
    status: "In Progress",
    budget: 64000,
    deadline: "2026-03-20",
    progress: 45,
    priority: "High",
    category: "Tech",
  },
  {
    id: "p22",
    clientId: "c9",
    name: "Retail POS Integration",
    status: "In Progress",
    budget: 48000,
    deadline: "2026-03-05",
    progress: 33,
    priority: "Medium",
    category: "Tech",
  },
  {
    id: "p23",
    clientId: "c10",
    name: "Hospital Scheduling Module",
    status: "In Progress",
    budget: 110000,
    deadline: "2026-03-25",
    progress: 50,
    priority: "Critical",
    category: "Tech",
  },
  {
    id: "p24",
    clientId: "c11",
    name: "Inventory Forecast Engine",
    status: "In Progress",
    budget: 36000,
    deadline: "2026-03-10",
    progress: 27,
    priority: "High",
    category: "Tech",
  },
  {
    id: "p25",
    clientId: "c12",
    name: "Cloud Security Audit",
    status: "In Progress",
    budget: 39000,
    deadline: "2026-02-28",
    progress: 60,
    priority: "Medium",
    category: "Tech",
  },
  {
    id: "p26",
    clientId: "c13",
    name: "Hotel Reservation API",
    status: "In Progress",
    budget: 82000,
    deadline: "2026-03-22",
    progress: 40,
    priority: "High",
    category: "Tech",
  },
  {
    id: "p27",
    clientId: "c1",
    name: "Security Patch Rollout",
    status: "In Progress",
    budget: 22000,
    deadline: "2026-03-01",
    progress: 80,
    priority: "High",
    category: "Tech",
  },
  {
    id: "p44",
    clientId: "c5",
    name: "Podcast Series Editing",
    status: "In Progress",
    budget: 27000,
    deadline: "2026-03-12",
    progress: 40,
    priority: "Medium",
    category: "Media",
  },
  {
    id: "p45",
    clientId: "c7",
    name: "Banner Ad Design",
    status: "In Progress",
    budget: 15000,
    deadline: "2026-03-08",
    progress: 55,
    priority: "Low",
    category: "Media",
  },
  {
    id: "p46",
    clientId: "c9",
    name: "Influencer Outreach",
    status: "In Progress",
    budget: 38000,
    deadline: "2026-03-18",
    progress: 30,
    priority: "High",
    category: "Media",
  },

  // TESTING - Status: Testing (10)
  {
    id: "p8",
    clientId: "c4",
    name: "Enterprise Upgrade Implementation",
    status: "Testing",
    budget: 92000,
    deadline: "2026-02-10",
    progress: 82,
    priority: "High",
    category: "Tech",
  },
  {
    id: "p9",
    clientId: "c6",
    name: "Trading Platform Optimization",
    status: "Testing",
    budget: 78000,
    deadline: "2026-02-20",
    progress: 88,
    priority: "High",
    category: "Tech",
  },
  {
    id: "p10",
    clientId: "c12",
    name: "Cloud Infrastructure Migration",
    status: "Testing",
    budget: 145000,
    deadline: "2026-02-28",
    progress: 91,
    priority: "Critical",
    category: "Tech",
  },
  {
    id: "p28",
    clientId: "c2",
    name: "Logistics Tracking Beta",
    status: "Testing",
    budget: 60000,
    deadline: "2026-02-25",
    progress: 75,
    priority: "Medium",
    category: "Tech",
  },
  {
    id: "p29",
    clientId: "c3",
    name: "Health App Feedback Module",
    status: "Testing",
    budget: 47000,
    deadline: "2026-02-22",
    progress: 68,
    priority: "Low",
    category: "Tech",
  },
  {
    id: "p30",
    clientId: "c5",
    name: "Analytics Beta Feature",
    status: "Testing",
    budget: 29000,
    deadline: "2026-02-18",
    progress: 83,
    priority: "High",
    category: "Tech",
  },
  {
    id: "p31",
    clientId: "c7",
    name: "Edu Portal Load Test",
    status: "Testing",
    budget: 32000,
    deadline: "2026-02-26",
    progress: 90,
    priority: "Medium",
    category: "Tech",
  },
  {
    id: "p32",
    clientId: "c8",
    name: "Construction Ticket System",
    status: "Testing",
    budget: 56000,
    deadline: "2026-02-24",
    progress: 70,
    priority: "High",
    category: "Tech",
  },
  {
    id: "p33",
    clientId: "c9",
    name: "Retail Checkout UX",
    status: "Testing",
    budget: 41000,
    deadline: "2026-02-27",
    progress: 95,
    priority: "Medium",
    category: "Tech",
  },
  {
    id: "p34",
    clientId: "c10",
    name: "Hospital API Compliance",
    status: "Testing",
    budget: 88000,
    deadline: "2026-02-29",
    progress: 89,
    priority: "Critical",
    category: "Tech",
  },
  {
    id: "p47",
    clientId: "c11",
    name: "Media Analytics Tool",
    status: "Testing",
    budget: 52000,
    deadline: "2026-02-26",
    progress: 78,
    priority: "High",
    category: "Media",
  },
  {
    id: "p48",
    clientId: "c12",
    name: "Ad Platform Integration",
    status: "Testing",
    budget: 61000,
    deadline: "2026-02-28",
    progress: 82,
    priority: "Medium",
    category: "Media",
  },

  // LIVE - Status: Live (10)
  {
    id: "p11",
    clientId: "c4",
    name: "CRM Platform Maintenance",
    status: "Live",
    budget: 25000,
    deadline: "2026-12-31",
    progress: 100,
    priority: "Medium",
    category: "Tech",
  },
  {
    id: "p12",
    clientId: "c10",
    name: "Hospital Management System",
    status: "Live",
    budget: 175000,
    deadline: "2026-12-31",
    progress: 100,
    priority: "Critical",
    category: "Tech",
  },
  {
    id: "p13",
    clientId: "c13",
    name: "Hotel Booking & Management",
    status: "Live",
    budget: 95000,
    deadline: "2026-12-31",
    progress: 100,
    priority: "High",
    category: "Tech",
  },
  {
    id: "p14",
    clientId: "c11",
    name: "Parts Inventory Tracking",
    status: "Live",
    budget: 42000,
    deadline: "2026-12-31",
    progress: 100,
    priority: "High",
    category: "Tech",
  },
  {
    id: "p35",
    clientId: "c1",
    name: "Security Maintenance Live",
    status: "Live",
    budget: 30000,
    deadline: "2026-12-31",
    progress: 100,
    priority: "High",
    category: "Tech",
  },
  {
    id: "p36",
    clientId: "c2",
    name: "Logistics Client Portal",
    status: "Live",
    budget: 110000,
    deadline: "2026-12-31",
    progress: 100,
    priority: "Critical",
    category: "Tech",
  },
  {
    id: "p37",
    clientId: "c3",
    name: "Healthcare Data Sync",
    status: "Live",
    budget: 60000,
    deadline: "2026-12-31",
    progress: 100,
    priority: "High",
    category: "Tech",
  },
  {
    id: "p38",
    clientId: "c5",
    name: "Analytics Module Live",
    status: "Live",
    budget: 45000,
    deadline: "2026-12-31",
    progress: 100,
    priority: "Medium",
    category: "Tech",
  },
  {
    id: "p39",
    clientId: "c6",
    name: "Trading Platform Live",
    status: "Live",
    budget: 80000,
    deadline: "2026-12-31",
    progress: 100,
    priority: "Critical",
    category: "Tech",
  },
  {
    id: "p40",
    clientId: "c7",
    name: "Edu Portal Live",
    status: "Live",
    budget: 50000,
    deadline: "2026-12-31",
    progress: 100,
    priority: "High",
    category: "Tech",
  },
  {
    id: "p49",
    clientId: "c8",
    name: "Social Media Dashboard",
    status: "Live",
    budget: 42000,
    deadline: "2026-12-31",
    progress: 100,
    priority: "Medium",
    category: "Media",
  },
  {
    id: "p50",
    clientId: "c10",
    name: "Broadcast Automation",
    status: "Live",
    budget: 90000,
    deadline: "2026-12-31",
    progress: 100,
    priority: "Critical",
    category: "Media",
  },
];

export const MOCK_ACTIVITIES = [
  {
    id: "a1",
    clientId: "c1",
    type: "email",
    description: "Sent weekly security report",
    date: "2023-10-25T14:30:00",
  },
  {
    id: "a2",
    clientId: "c2",
    type: "call",
    description: "Introductory call with James",
    date: "2023-10-28T10:00:00",
  },
  {
    id: "a3",
    clientId: "c1",
    type: "meeting",
    description: "API integration planning session",
    date: "2023-11-15T11:00:00",
  },
  {
    id: "a4",
    clientId: "c4",
    type: "email",
    description: "Sent Q4 performance metrics report",
    date: "2023-11-20T09:30:00",
  },
  {
    id: "a5",
    clientId: "c2",
    type: "call",
    description: "Budget approval discussion",
    date: "2023-11-18T14:15:00",
  },
  {
    id: "a6",
    clientId: "c3",
    type: "email",
    description: "Sent facility audit checklist",
    date: "2023-11-17T16:45:00",
  },
  {
    id: "a7",
    clientId: "c5",
    type: "meeting",
    description: "Demo of new analytics dashboard",
    date: "2023-11-16T10:00:00",
  },
  {
    id: "a8",
    clientId: "c6",
    type: "call",
    description: "Market expansion strategy discussion",
    date: "2023-11-19T15:30:00",
  },
  {
    id: "a9",
    clientId: "c8",
    type: "email",
    description: "Construction project milestone review",
    date: "2023-11-21T13:00:00",
  },
  {
    id: "a10",
    clientId: "c10",
    type: "meeting",
    description: "Healthcare compliance verification",
    date: "2023-11-22T11:30:00",
  },
  {
    id: "a11",
    clientId: "c7",
    type: "call",
    description: "Student management features walkthrough",
    date: "2023-11-20T14:00:00",
  },
  {
    id: "a12",
    clientId: "c12",
    type: "email",
    description: "API partnership documentation sent",
    date: "2023-11-19T09:45:00",
  },
];

export const MOCK_ENQUIRIES = [
  // INBOX - New/Read Status (10)
  {
    id: "e1",
    name: "Tony Stark",
    email: "tony@starkindustries.com",
    phone: "+1 (555) 999-8888",
    website: "https://starkindustries.com",
    message:
      "We are looking for a secure CRM solution to manage our defense contracts. Needs to be air-gapped compliant.",
    date: "2023-10-29T09:15:00",
    status: "new",
  },
  {
    id: "e2",
    name: "Sarah Williams",
    email: "sarah.w@appleseed.com",
    phone: "+1 (555) 123-4567",
    website: "https://appleseed.com",
    message:
      "Looking for a CRM with strong reporting features. Currently using spreadsheets.",
    date: "2023-11-22T10:30:00",
    status: "new",
  },
  {
    id: "e3",
    name: "Michael Chen",
    email: "michael@horizontech.io",
    phone: "+86 10 1234 5678",
    website: "https://horizontech.io",
    message: "Interested in cloud-based solution for our growing sales team.",
    date: "2023-11-22T11:45:00",
    status: "new",
  },
  {
    id: "e4",
    name: "Emma Johnson",
    email: "emma.johnson@sparkledesign.co.uk",
    phone: "+44 20 7946 0958",
    website: "https://sparkledesign.co.uk",
    message: "Need CRM for managing design projects and client communications.",
    date: "2023-11-22T14:20:00",
    status: "new",
  },
  {
    id: "e5",
    name: "Dmitri Volkov",
    email: "dmitri@siberian-corp.ru",
    phone: "+7 495 123 4567",
    website: "https://siberian-corp.ru",
    message: "Expanding operations to India. Need scalable CRM solution.",
    date: "2023-11-21T09:00:00",
    status: "new",
  },
  {
    id: "e6",
    name: "Lucia Martinez",
    email: "lucia@globaltrade.mx",
    phone: "+52 55 1234 5678",
    website: "https://globaltrade.mx",
    message:
      "Looking for multilingual CRM to manage Latin American operations.",
    date: "2023-11-21T13:15:00",
    status: "new",
  },
  {
    id: "e7",
    name: "Hassan Al-Rashid",
    email: "hassan@dubaiventures.ae",
    phone: "+971 4 123 4567",
    website: "https://dubaiventures.ae",
    message: "Enterprise CRM needed for real estate management.",
    date: "2023-11-20T10:30:00",
    status: "read",
  },
  {
    id: "e8",
    name: "Yuki Tanaka",
    email: "yuki.tanaka@tokyotech.jp",
    phone: "+81 3 1234 5678",
    website: "https://tokyotech.jp",
    message: "Interested in API documentation for integration with our system.",
    date: "2023-11-20T15:45:00",
    status: "read",
  },
  {
    id: "e9",
    name: "Isabella Romano",
    email: "isabella@milanofashion.it",
    phone: "+39 02 1234 567",
    website: "https://milanofashion.it",
    message: "Fashion retail CRM with inventory management features.",
    date: "2023-11-19T11:20:00",
    status: "read",
  },
  {
    id: "e10",
    name: "Björn Andersson",
    email: "bjorn@stockholm-consulting.se",
    phone: "+46 8 123 4567",
    website: "https://stockholm-consulting.se",
    message: "Need CRM for managing consultant assignments and billing.",
    date: "2023-11-19T09:30:00",
    status: "read",
  },

  // ON HOLD - Status: hold (10)
  {
    id: "e11",
    name: "James Wilson",
    email: "james.w@brownstone.com",
    phone: "+1 (555) 234-5678",
    website: "https://brownstone.com",
    message: "Very interested but need to get budget approval first.",
    date: "2023-11-18T10:00:00",
    status: "hold",
    holdReason: "Awaiting budget approval",
  },
  {
    id: "e12",
    name: "Catherine Lee",
    email: "catherine@silverlake.com",
    phone: "+1 (555) 345-6789",
    website: "https://silverlake.com",
    message: "Evaluating multiple solutions. Will decide in Q1 2024.",
    date: "2023-11-17T14:30:00",
    status: "hold",
    holdReason: "Evaluating competitors",
  },
  {
    id: "e13",
    name: "Robert Thompson",
    email: "robert.t@goldenstatetech.com",
    phone: "+1 (555) 456-7890",
    website: "https://goldenstatetech.com",
    message: "Waiting for our IT director to return from vacation.",
    date: "2023-11-16T09:15:00",
    status: "hold",
    holdReason: "Key decision maker unavailable",
  },
  {
    id: "e14",
    name: "Sofia Garcia",
    email: "sofia.g@buenosaires.com.ar",
    phone: "+54 11 2345 6789",
    website: "https://buenosaires.com.ar",
    message: "Need to complete current project migration first.",
    date: "2023-11-15T16:45:00",
    status: "hold",
    holdReason: "Pending project completion",
  },
  {
    id: "e15",
    name: "David Cohen",
    email: "david@telaviv-solutions.co.il",
    phone: "+972 3 123 4567",
    website: "https://telaviv-solutions.co.il",
    message: "Company restructuring in progress. Will revisit in 6 weeks.",
    date: "2023-11-14T11:00:00",
    status: "hold",
    holdReason: "Company restructuring",
  },
  {
    id: "e16",
    name: "Natasha Kozlov",
    email: "natasha@moscow-media.ru",
    phone: "+7 495 234 5678",
    website: "https://moscow-media.ru",
    message: "Excellent solution but need local support presence first.",
    date: "2023-11-13T13:20:00",
    status: "hold",
    holdReason: "Seeking local support",
  },
  {
    id: "e17",
    name: "Fatima Al-Mansouri",
    email: "fatima@qatarenterprises.qa",
    phone: "+974 4123 4567",
    website: "https://qatarenterprises.qa",
    message: "Need to sync with parent company headquarters.",
    date: "2023-11-12T10:45:00",
    status: "hold",
    holdReason: "Waiting for parent company approval",
  },
  {
    id: "e18",
    name: "Marcel Dupont",
    email: "marcel@parisinnovation.fr",
    phone: "+33 1 2345 67890",
    website: "https://parisinnovation.fr",
    message: "Interested but evaluating on-premise vs cloud solution.",
    date: "2023-11-11T14:00:00",
    status: "hold",
    holdReason: "Evaluating deployment options",
  },
  {
    id: "e19",
    name: "Klaus Mueller",
    email: "klaus@berlin-engineering.de",
    phone: "+49 30 1234 5678",
    website: "https://berlin-engineering.de",
    message: "Need compliance certification approval before proceeding.",
    date: "2023-11-10T09:30:00",
    status: "hold",
    holdReason: "Compliance review in progress",
  },
  {
    id: "e20",
    name: "Olivia Amsterdam",
    email: "olivia@dutch-trading.nl",
    phone: "+31 20 123 4567",
    website: "https://dutch-trading.nl",
    message: "Positive feedback but board approval needed.",
    date: "2023-11-09T15:15:00",
    status: "hold",
    holdReason: "Awaiting board approval",
  },

  // DISMISSED - Status: dismissed (10)
  {
    id: "e21",
    name: "Gordon Price",
    email: "gordon@lookalike.com",
    phone: "+1 (555) 567-8901",
    website: "https://lookalike.com",
    message: "Our current solution meets all our needs.",
    date: "2023-11-08T10:00:00",
    status: "dismissed",
  },
  {
    id: "e22",
    name: "Patricia Moore",
    email: "patricia.m@exclusive.com",
    phone: "+1 (555) 678-9012",
    website: "https://exclusive.com",
    message: "Price point is too high for our budget constraints.",
    date: "2023-11-07T11:30:00",
    status: "dismissed",
  },
  {
    id: "e23",
    name: "Gerald Knight",
    email: "gerald@old-company.com",
    phone: "+1 (555) 789-0123",
    website: "https://old-company.com",
    message: "Not compatible with our legacy systems. Cannot upgrade.",
    date: "2023-11-06T14:15:00",
    status: "dismissed",
  },
  {
    id: "e24",
    name: "Victoria Stone",
    email: "victoria.s@niche-market.com",
    phone: "+1 (555) 890-1234",
    website: "https://niche-market.com",
    message: "Going with competitor product. Good luck!",
    date: "2023-11-05T09:45:00",
    status: "dismissed",
  },
  {
    id: "e25",
    name: "Raymond Powell",
    email: "raymond@small-biz.com",
    phone: "+1 (555) 901-2345",
    website: "https://small-biz.com",
    message: "Too complex for our simple needs.",
    date: "2023-11-04T16:30:00",
    status: "dismissed",
  },
  {
    id: "e26",
    name: "Susan Banks",
    email: "susan@closed-shop.com",
    phone: "+1 (555) 012-3456",
    website: "https://closed-shop.com",
    message: "Company is closing operations. No longer need.",
    date: "2023-11-03T13:00:00",
    status: "dismissed",
  },
  {
    id: "e27",
    name: "Thomas Ellis",
    email: "thomas.e@sold-out.com",
    phone: "+1 (555) 111-2222",
    website: "https://sold-out.com",
    message: "Company was acquired. Different CRM strategy now.",
    date: "2023-11-02T10:20:00",
    status: "dismissed",
  },
  {
    id: "e28",
    name: "Margaret Pierce",
    email: "margaret@unqualified.com",
    phone: "+1 (555) 222-3333",
    website: "https://unqualified.com",
    message: "Enquiry does not meet our qualification criteria.",
    date: "2023-11-01T11:50:00",
    status: "dismissed",
  },
  {
    id: "e29",
    name: "Frank Dixon",
    email: "frank.d@spam-risk.com",
    phone: "+1 (555) 333-4444",
    website: "https://spam-risk.com",
    message: "Suspicious enquiry - marked as potential spam.",
    date: "2023-10-31T14:40:00",
    status: "dismissed",
  },
  {
    id: "e30",
    name: "Helen Garcia",
    email: "helen@incorrect-fit.com",
    phone: "+1 (555) 444-5555",
    website: "https://incorrect-fit.com",
    message:
      "Looking for solution we don't offer. Redirected to alternative vendor.",
    date: "2023-10-30T09:10:00",
    status: "dismissed",
  },
];

export const ANALYTICS_DATA = [
  { name: "May", enquiries: 12, clients: 8, projects: 2, engagement: 65 },
  { name: "Jun", enquiries: 18, clients: 10, projects: 4, engagement: 72 },
  { name: "Jul", enquiries: 15, clients: 12, projects: 5, engagement: 70 },
  { name: "Aug", enquiries: 24, clients: 15, projects: 6, engagement: 78 },
  { name: "Sep", enquiries: 32, clients: 18, projects: 9, engagement: 82 },
  { name: "Oct", enquiries: 28, clients: 22, projects: 12, engagement: 88 },
];

export const QUARTERLY_ANALYTICS_DATA = [
  { name: "Q1 2023", enquiries: 45, clients: 32, projects: 8, engagement: 62 },
  { name: "Q2 2023", enquiries: 58, clients: 40, projects: 12, engagement: 70 },
  { name: "Q3 2023", enquiries: 75, clients: 55, projects: 18, engagement: 79 },
  { name: "Q4 2023", enquiries: 88, clients: 68, projects: 24, engagement: 85 },
];
